### ISSUE TITLE
server.jar and precipitate jar are not found in 7.7.0.20200930 release

### ISSUE THREAD

**Issue by sjoel** [Axway-API-Management-Plus/apim-password-cert-env#10]
Hello team,

The pom.xml wouldn't compile with "mvn clean package" or "mvn -U clean install"

by uploading the packages apigw-common, vordel-trace, vordel-common, es-core, vordel-system, vordel-config jar files with respect to  the 7.7.0.20200930 release and server.jar and precipiate.jar are not found

Is there any alternative jar files that are to be used to replace them? 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project axway-apim-env-module: Compilation failure: Compilation failure: 
[ERROR] /Users/xxx/axway/axway-apim-env-module/src/main/java/com/axway/ExternalConfigLoader.java:[46,33] cannot access com.vordel.runtime.interfaces.ServiceInfo
[ERROR]   class file for com.vordel.runtime.interfaces.ServiceInfo not found
[ERROR] /Users/xxx/axway/axway-apim-env-module/src/main/java/com/axway/ExternalConfigLoader.java:[227,15] cannot access com.vordel.common.Dictionary
[ERROR]   class file for com.vordel.common.Dictionary not found
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project axway-apim-env-module: Compilation failure

**Comment by rathnapandi** [comment]
Hi @sjoel,
server.jar and precipiate.jar names are changed.  Below one from November release, please update the version based on September release. 


<dependency>
            <groupId>vordel-apigateway</groupId>
            <artifactId>vordel-apigateway</artifactId>
            <scope>system</scope>
            <version>${api.version}</version>
            <systemPath>${apim.lib.path}/vordel-apigateway-7.7.0.20201130-5.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>vordel-core-runtime</groupId>
            <artifactId>vordel-core-runtime</artifactId>
            <scope>system</scope>
            <version>${api.version}</version>
            <systemPath>${apim.lib.path}/vordel-core-runtime-7.7.0.20201130-5.jar</systemPath>
        </dependency>

Reference: https://github.com/Axway-API-Management-Plus/apim-password-cert-env/blob/connect2urlsslauth/pom.xml

Thanks
Rathna

**Comment by rathnapandi** [comment]
jar files are updated.
