### ISSUE TITLE
PKCS12 not importing the CA chain

### ISSUE THREAD

**Issue by cijujoseph** [Axway-API-Management-Plus/apim-password-cert-env#5]
PKCS12 import to update the https listener certificate via `certandkey_secureport` variable is not importing the CA cert chain.

Steps to reproduce:

- Create p12 file using the openssl

 
```
openssl pkcs12 -inkey <key> \
    -in <cert> \
    -export -out cert.p12 \
    -password pass:<put password> \
    -chain -CAfile <CA cert chain pem> \
    -name OAuthCertificate
```

- Then replace it with certandkey_secureport. 

- Once the endpoint is up and running, inspect the certs via the openssl command 

`openssl s_client -showcerts -servername <host name> -connect <host name>:<port>`

**Comment by jordanwalsh23** [comment]
Hi @rathnapandi - when do you envisage that your commit will be merged to master?

**Comment by rathnapandi** [comment]
@jordanwalsh23 I am working on it, will update you soon.
